In [1]:
import pgeocode
import pandas as pd
from fng_api import *

In [2]:
gb = pgeocode.Nominatim('gb')
# gb.query_postal_code("G34 0EG")

In [3]:
postcodes_df = pd.read_csv("smalluser-glasgow.csv")

/tmp/ipykernel_33513/75741456.py:1: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  postcodes_df = pd.read_csv("smalluser-glasgow.csv")

In [4]:
postcodes_df

,Postcode,PCSector,PCDistrict,Date of Introduction,Date of Deletion,Grid Reference Easting,Grid Reference Northing,Council_Area,Elec_Ward 07,Elec_Ward 99,...,Reg Outcome Area CPP,Comm Health Parts 2011,Comm Health Parts 2012,CHP Sub Sector 2011,Strategic Dev Plan Area,Mult Storey Accom Ind,Student Accom Ind,Sheltered Housing Accom Ind,Gridlink Coordinate Indicator,Split Indicator
0,G1 1BL,G1 1,G1,01/09/1985,NaN,259718.0,665071.0,17,1710.0,1727.0,...,NaN,S03000043,S03000043,S26000017,S11000004,NaN,NaN,NaN,Y,N
1,G1 1BQ,G1 1,G1,10/04/2008,NaN,259329.0,665167.0,17,1710.0,1727.0,...,NaN,S03000043,S03000043,S26000017,S11000004,NaN,NaN,NaN,Y,N
2,G1 1DA,G1 1,G1,01/08/1973,NaN,259213.0,665244.0,17,1710.0,1727.0,...,NaN,S03000043,S03000043,S26000017,S11000004,NaN,NaN,NaN,Y,N
3,G1 1DG,G1 1,G1,13/01/2003,NaN,259283.0,665312.0,17,1710.0,1727.0,...,NaN,S03000043,S03000043,S26000017,S11000004,NaN,NaN,NaN,Y,N
4,G1 1DJ,G1 1,G1,01/03/1987,NaN,259503.0,665193.0,17,1710.0,1727.0,...,NaN,S03000043,S03000043,S26000017,S11000004,NaN,NaN,NaN,Y,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15235,G78 1TD,G78 1,G78,01/08/1973,NaN,251646.0,659057.0,17,1703.0,1762.0,...,NaN,S03000043,S03000043,S26000019,S11000004,NaN,NaN,NaN,Y,N
15236,G78 1TE,G78 1,G78,01/08/1973,NaN,251620.0,659516.0,17,1703.0,1762.0,...,NaN,S03000043,S03000043,S26000019,S11000004,NaN,NaN,NaN,Y,N
15237,G78 1TF,G78 1,G78,01/08/1973,NaN,251610.0,659747.0,17,1703.0,1761.0,...,NaN,S03000043,S03000043,S26000019,S11000004,NaN,NaN,NaN,Y,N
15238,G81 1ETB,G81 1,G81,01/02/1989,NaN,251220.0,669610.0,17,1713.0,1706.0,...,NaN,S03000043,S03000043,S26000018,S11000004,NaN,NaN,NaN,Y,Y
15239,G81 1EWB,G81 1,G81,01/08/1973,NaN,251090.0,669370.0,17,1713.0,1706.0,...,NaN,S03000043,S03000043,S26000018,S11000004,NaN,NaN,NaN,Y,Y

In [5]:
def fetch_postcode_data(postcode):
    try:
        data = gb.query_postal_code(postcode)
        return f"{data.latitude}, {data.longitude}"
    except:
        return None

In [6]:
postcodes_df['latlong'] = postcodes_df['Postcode'].apply(lambda x: fetch_postcode_data(x))

In [7]:
postcodes_df[['latitude', 'longitude']] = postcodes_df['latlong'].str.split(',', expand=True)

In [8]:
final_postcodes_df = postcodes_df[
    ['Postcode', 'latitude', 'longitude']
]

final_postcodes_df.columns = ['postcode', 'latitude', 'longitude']

In [9]:
final_postcodes_df.to_csv("postcode_latlong.csv", index=False)